---
title: "Dormancy in metacommunities"
author: "Nathan Wisnoski"
date: "7/16/2018"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())

library(tidyverse)
library(vegan)
library(progress)
library(viridis)
library(adespatial)
library(igraph)


source("make_landscape.R")
```


### Define model conditions
```{r}
set.seed(47405)

tsteps <- 1000      # Number of time steps in model
dt <- 1    # precision for euler method integration

M <- 50 # Number of sites

```

# Generate the landscape
```{r}
# Generate the landscape randomly, 
# coarse parameter is the spatial structure, bigger values more structure, 
# random is x/y-slope = 0 and coarse ~ 1
# xslope and yslope control directional gradients
landscape <- make.landscape(sites = M, xslope = 0.1, yslope = 0, coarse = 10000, envvars = 1)
coords <- landscape$coords
env <- landscape$env
plot(coords, pch = 20, cex = 2, col = viridis(M)[rank(env)], asp = 1,
     xlim = c(0,100), ylim = c(0,100))


# Generate patch connectivity using dbMEM and visualize
geo.dists <- dist(landscape$coords)
mc.weighted <- listw.candidates(coords, nb = 'dnear', 
                                weights = "fup",
                                d2 = 1/2*max(geo.dists))
#mc.weighted <- listw.candidates(coords, nb = 'pcnm', weights = 'fdown')

plot(coords, pch = 20, cex = 2, col = viridis(M)[rank(env)], asp = 1,
     xlim = c(0,100), ylim = c(0,100))
plot(mc.weighted[[1]], coords, col = adjustcolor("black", alpha.f = 0.1), add = T)


neigh <- mc.weighted[[1]]$neighbours
ws <- mc.weighted[[1]]$weights

spatial.edges <- create.edge.list(neigh)
spatial.weights <- create.edge.list(ws)[,-1]

spatial.graph <- graph_from_edgelist(spatial.edges)
E(spatial.graph)$weight <- spatial.weights
plot(spatial.graph)
adj.mat <- as_adjacency_matrix(spatial.graph, attr = "weight")
adj.mat <- as.matrix(adj.mat)
adj.mat
```

### Define parameters
```{r}
# 
# # density independent growth
# max.growth <- runif(S) + 1
# # optimal env conditions
# o.comp <- runif(S, min = range(env)[1], max = range(env)[2])
# # niche breadths, 
# # low nb.spec = more specialists, high nb.spec = more generalists
# # low nb.var = most species follow nb.spec, high nb.var = greater mix of species strategies
# nb.spec <- 1
# nb.var <- 1
# sig.comp <- rgamma(S, shape = nb.spec, scale = nb.var)
# 
# d.cctradeoff <- function(max.growth, strength = 0.5){
#   -max.growth*strength + abs(min(-max.growth*strength))
# }
# # d <- 0.01
# 
# 
# # dorm <- 0.3
```

### Metacom Functions
```{r}
R.jx <- function(env.xy, max.growth, o.comp, sig.comp){
  max.growth * exp(-((env.xy - o.comp)^2/(2*sig.comp^2)))
}
  
competition <- function(N,a) {
  return( 1 / ( 1 + a*(sum(N))))
}
  
# disperse <- function(d, N, M){
#   d*((rowSums(N) - N) / (M-1) - N)
# }
# disperse <- function(d, adj.mat, N, M, scaling = 0.01){
#   
#   # calculate dispersing individuals
#   dispersers = d * t(N)
#   
#   # convert geographic distances to dispersal rates
#   connectivity.mat = exp(-as.matrix(geo.dists)*scaling)
#   
#   # disperse individuals 
#   dispersers = t(connectivity.mat %*% dispersers)
#   return(dispersers)
# }


disperse <- function(d, adj.mat, N, M){

  # calculate dispersing individuals
  dispersers = d * t(N)

  # standardize geographic distances, establish barriers via adjacency mat
  connectivity.mat = stdize(as.matrix(geo.dists)) * adj.mat

  # disperse individuals
  dispersers = t(connectivity.mat %*% dispersers)
  return(dispersers)
}


# further optimum is from environment, and smaller the niche breadth (sig comp), dormancy transitions faster
dormancy <- function(env.xy, max.dorm, o.comp, sig.comp){
  
  max.dorm * (1 - exp(-((env.xy - o.comp)^2/(2*sig.comp^2))))
  
  # # if growth * competition is < 1, shift towards dormancy
  # D[which(R.t * comp.t < 1)] <- N[which(R.t * comp.t < 1)] * (dorm)
  # N[which(R.t * comp.t < 1)] <- N[which(R.t * comp.t < 1)] * (1-dorm)
  # 
  # # if growth * competition > 1 and there are dormant propagules, reactivate
  # N[which(R.t * comp.t > 1 & D.t > 0)] <- D[which(R.t * comp.t > 1 & D.t > 0)] * dorm
  # D[which(R.t * comp.t > 1 & D.t > 0)] <- D[which(R.t * comp.t > 1 & D.t > 0)] * (1-dorm)
  
  # return(list(N = N, D = D))
}

# higher responsiveness is what proportion of the dormant propagules can reactivate at once
# higher precision means that the conditions that would trigger responses have to be much closer to optimum
resuscitate <- function(env.xy, responsiveness, o.comp, precision){
  
  responsiveness * exp(-((env.xy - o.comp)^2/(2*(1/precision)^2)))
  
  # # if growth * competition is < 1, shift towards dormancy
  # D[which(R.t * comp.t < 1)] <- N[which(R.t * comp.t < 1)] * (dorm)
  # N[which(R.t * comp.t < 1)] <- N[which(R.t * comp.t < 1)] * (1-dorm)
  # 
  # # if growth * competition > 1 and there are dormant propagules, reactivate
  # N[which(R.t * comp.t > 1 & D.t > 0)] <- D[which(R.t * comp.t > 1 & D.t > 0)] * dorm
  # D[which(R.t * comp.t > 1 & D.t > 0)] <- D[which(R.t * comp.t > 1 & D.t > 0)] * (1-dorm)
  
  # return(list(N = N, D = D))
}
  

synchronize.env <- function(env, t, period, moran = F){
  if(moran == T){
    env * (sin(2*pi*t/period) + 1)/2
  }
  else (env + sin(2*pi*t/period) + 1)/3
}

asynchronize.env <- function(env, t, period, moran = F){
  if(moran == T){
    env * (sin(seq(1, M)*2*pi/M + (2*pi/period)*t) + 1)/2
  }
  else (env + sin(seq(1, M)*2*pi/M + (2*pi/period)*t) + 1)/3
}
```


### Define model
```{r}
run_sim <- function(d, env.type, disturbance, ...){
  
  
  # initialize result array, Species X Sites X Time 
  results.N <- array(NA, c(S, M, tsteps), 
                     dimnames = list(c(paste0("sp",1:S)), c(paste0("site",1:M)), c(1:tsteps)))
  results.D <- array(NA, c(S, M, tsteps),
                     dimnames = list(c(paste0("sp",1:S)), c(paste0("site",1:M)), c(1:tsteps)))
  
  # add active species to sites, seed banks are empty
  results.N[,,1] <- matrix(rpois(M*S, 1), nrow = S, ncol = M)
  results.D[,,1] <- matrix(0, nrow = S, ncol = M)
  
  # create joint summary results output
  res <- matrix(NA, ncol = 5, nrow = 0)
  
  # perform sims once with and without dormancy
  for(yes.dormancy in c(T,F)){
    for(t in 1:(tsteps / dt - 1)){
      # Init or update progress bar
      if(t == 1) pb <- progress_bar$new(total = (tsteps / dt), force = T)
      pb$update(ratio = t/(tsteps / dt))
      
      N.t <- results.N[,,t]
      D.t <- results.D[,,t]
      
      # if env.type is not static, either randomize it or oscillate
      if(env.type == "random"){
        env[,1] <- runif(length(env))
      }
      if(env.type == "synchronous"){
        env[,1] <- synchronize.env(env = env[,1], t = t, period = period)
      }
      if(env.type == "asynchronous"){
        env[,1] <- asynchronize.env(env = env[,1], t = t, period = period)
      }
      
      if(disturbance == T){
        if(runif(1) < dist.freq){
          # randomly choose site to disturb
          N.t[,sample(1:M, size = ceiling(dist.extent*M), replace = F)] <- 0
          
        } 
      }
      
      # calculates growth rates for each species (rows) in each site (cols)
      # dimensions = S x M
      R.t <- apply(X = env, MARGIN = 1, FUN = R.jx, max.growth, o.comp, sig.comp)
      
      # calculate competition at this time
      comp.t <- apply(N.t, MARGIN = 2, FUN = competition, a = a)
      
      # if there is dormancy, then perform functions
      if(yes.dormancy){
        now.dormant <- N.t * apply(X = env, MARGIN = 1, FUN = dormancy, max.dorm, o.comp, sig.comp)
        now.active <- D.t * apply(X = env, MARGIN = 1, FUN = resuscitate, responsiveness, o.comp, precision)
        N.t0 <- N.t - now.dormant + now.active
        D.t <- D.t - now.active + now.dormant
      }
      
      
      # growth
      N.t0 <- R.t * N.t * comp.t
      
      # separate dispersers, then calculate dispersal, and re-add
      
      N.t1 <- N.t0 * (1-d) + disperse(d = d, N = N.t0, M = M, adj.mat = adj.mat)
      D.t1 <- D.t * (1-d) + disperse(d = d, N = D.t, M = M, adj.mat = adj.mat)
      
      results.N[,,t+1] <- ifelse(N.t1 > .1, N.t1, 0)
      results.D[,,t+1] <- ifelse(D.t1 > .1, D.t1, 0) 
    }
    
  
    # summarize alpha, beta, and gamma diversity for this run
    alpha <- mean(specnumber(t(results.N[,,tsteps] + 0*results.D[,,tsteps])))
    gamma <- sum(rowSums(results.N[,,t] + 0*results.D[,,tsteps]) > 0)
    beta <- gamma / alpha
    beta <- ifelse(is.nan(beta), 0, beta)
    
    # write results to the matrix
    res <- rbind(res, 
                 cbind(dispersal = d, 
                       dormancy = as.numeric(yes.dormancy), 
                       alpha = alpha, 
                       beta = beta, 
                       gamma = gamma))
  }


return(res)
}


```


```{r}
set.seed(47405)
nsims <- 1

S <- 20 # Number of species

# set up dispersal vector
# d.list <- as.list(seq(0,1, by = 0.05))
# d.list <- as.list(c(seq(from = 1, to = 9, by = 4)*1e-9,
# #  seq(from = 1, to = 9, by = 4)*1e-8,
#   seq(from = 1, to = 9, by = 4)*1e-7,
# #  seq(from = 1, to = 9, by = 4)*1e-6,
#   seq(from = 1, to = 9, by = 4)*1e-5,
#   seq(from = 1, to = 9, by = 4)*1e-4,
#   seq(from = 1, to = 9, by = 4)*1e-3,
#   seq(from = 1, to = 9, by = 4)*1e-2,
#   seq(from = 1, to = 9, by = 4)*1e-1, 1))

d.list <- list(1e-3, 1e-2, 0.1, 0.5, 1)
# d.list <- list(1e-3)
running.out <- matrix(NA, nrow = 0, ncol = 5)

growth.breadth.to <- -0.5
for(i in 1:nsims){
  print(paste("Simulation",i,"of",nsims,"."))
  # update params
  # density independent growth
  max.growth <- runif(S) + 1
  # max.growth <- rep(1.2, S)
  # optimal env conditions
  # o.comp <- runif(S, min = range(env)[1], max = range(env)[2])
  o.comp <- 1/(S+1) * seq(1:S)
  # niche breadths, 
  sig.comp <- 1 + growth.breadth.to * max.growth 
  # sig.comp <- rep(1, S)
  plot(sig.comp, max.growth)
  
  # dormancy params # these don't really have a big effect on the outcomes in static or random environments
  max.dorm <- .5
  responsiveness <- .5
  precision <- 1
  
  # beverton-holt alpha
  a <- 1e-5

  # disturbance frequency if disturbance
  dist.freq <- 0.05 # freq of a disturbance
  dist.extent <- 0.1 # what fraction of patches disturbed
  
  # options for env.type = "static", "random", "synchronous", "asynchronous"
  # period controls the degree of temporal autocorrelation. 
  # If period > tsteps, high autocorrelation. If period << tsteps, low temp autocorrelation
  period = 100
  out <- lapply(d.list, FUN = run_sim, env.type = "asynchronous", disturbance = F,
                period, dist.freq, dist.extent)
  # unlist(out)[seq(1:length(unlist(out)))]
  
  for(i in 1:length(out)){
    running.out <- rbind(running.out, out[[i]])
  }
  
  # out <- matrix(unlist(out), ncol = 5, byrow = T)
  # running.out <- rbind(running.out,out)
}



# d.list <- list(0, 0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 0.5, 0.75, 0.9, 1)
# out <- lapply(d.list, FUN = run_sim)
# out <- matrix(unlist(out), ncol = 4, byrow = T)
colnames(running.out) <- c("dispersal", "dormancy", "alpha", "beta", "gamma")
running.out
running.out %>% as_tibble() %>%
  mutate(dormancy = factor(dormancy, levels = c(0,1), labels = c("no", "yes"))) %>% 
  gather(alpha, beta, gamma, -dormancy, key = "scale", value = "diversity") %>%
  group_by(dormancy, dispersal, scale) %>% 
  mutate(mean_div = mean(diversity), se = sd(diversity)/n()) %>%
  ggplot(aes(x = dispersal, y = mean_div, color =  dormancy)) + 
  geom_point(alpha = 0.25, size = 2) + 
  geom_errorbar(aes(ymin = mean_div - se, ymax = mean_div + se)) +
  geom_line(alpha = 0.5) +
  theme_bw() +
  facet_grid(scale ~ ., scales = "free_y") +
  scale_x_log10() +
  ggsave("figures/diversity-paritioning-and-dispersal.png", width =4, heigh = 8, units = "in")
```

### plot model output
```{r}
richness.dynamics <- matrix(NA, ncol = M, nrow = tsteps)
colnames(richness.dynamics) <- paste0("site",1:M)

for(t in 1:tsteps){
  richness.dynamics[t,] <- as.vector(specnumber(t(results.N[,,t])))
}

gamma.dynamics <- vector(length = tsteps)
for(t in 1:tsteps){
  gamma.dynamics[t] <- sum(rowSums(results.N[,,t]) > 0)
}

diversity.dynamics <- data.frame(time = seq(1, tsteps), alpha = rowMeans(richness.dynamics), gamma = gamma.dynamics)

diversity.dynamics %>% 
  mutate(beta = gamma/alpha) %>% 
  gather(alpha, beta, gamma, key = "scale", value = "diversity") %>% 
  ggplot(aes(x = time, y = diversity, color = scale)) + 
  geom_point() + 
  geom_line()
```

